# This file was generated by GoReleaser. DO NOT EDIT.
cask "nlocal" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "dafaa6fd6cd90f3987e52a8114d5087bdaf251e8cc575e9fa866fa015fdc6195"
      url "https://github.com/Xanda-Labs/homebrew-tap/releases/download/v#{version}/nlocal_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1d773c7d2f078077208615591b7cd9c3eb71560566668640bf97ffee6ca1c2b4"
      url "https://github.com/Xanda-Labs/homebrew-tap/releases/download/v#{version}/nlocal_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6925ccdeef715e2fc6e45ec951619864d4c022d25abb1831b0f7760649618a89"
      url "https://github.com/Xanda-Labs/homebrew-tap/releases/download/v#{version}/nlocal_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "54c57cab4b74c61e9bae29ace995ac2e36074964edd189888dd0ec96cb63a65f"
      url "https://github.com/Xanda-Labs/homebrew-tap/releases/download/v#{version}/nlocal_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nlocal"
  desc "Expose your localhost. Instantly."
  homepage "https://nlocal.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nlocal"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/nlocal"]
    end
  end

  # No zap stanza required
end
