# This file was generated by GoReleaser. DO NOT EDIT.
cask "nlocal" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "21a2e0f0e8dab001daacacc6f6fbf6a401f4a526bf878d5090591c83161ad400"
      url "https://github.com/Xanda-Labs/nlocal/releases/download/v#{version}/nlocal_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "22c8e189206f23b1a055c5551a5aa0b305bf2cac752d0320d507849d52f4a4c6"
      url "https://github.com/Xanda-Labs/nlocal/releases/download/v#{version}/nlocal_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "60e6f8e3346b480b54fb133d8e4481d71cef06ffedbd35dae65b7a0d64e03870"
      url "https://github.com/Xanda-Labs/nlocal/releases/download/v#{version}/nlocal_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "17df703efe6786779406d4222a607a497f62a7547838f8a34f954bdab82acced"
      url "https://github.com/Xanda-Labs/nlocal/releases/download/v#{version}/nlocal_#{version}_linux_amd64.tar.gz"
    end
  end

  name "nlocal"
  desc "Expose your localhost. Instantly."
  homepage "https://nlocal.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "nlocal"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/nlocal"]
    end
  end

  # No zap stanza required
end
